### ISSUE TITLE
Create a copy if downloading the data is too heavy for the udalmap server

### ISSUE THREAD

**Issue by numeroteca** [BilbaoDataLab/udalmap-r-maps#1]
If downloading the data is too heavy for the udalmap server (https://github.com/BilbaoDataLab/session-20161027-r/blob/master/udalmap/udalmap.R#L11)... It would be a possibility to create a copy of the data in this repo .

I'd would put that part of the script optional, to avoid overloads. What do you think?

**Comment by gkobeaga** [comment]
Closing issue because required data has been included in the repo.
https://github.com/BilbaoDataLab/udalmap-r-maps/blob/master/data/
