### ISSUE TITLE
¿En qué orden hay que correr los scripts?

### ISSUE THREAD

**Issue by numeroteca** [BilbaoDataLab/udalmap-r-maps#2]
En qué orden hay que correr los scripts. Hay 4 numerados pero udalmap.R no lo está: https://github.com/BilbaoDataLab/session-20161027-r/tree/master/udalmap

**Comment by Haxier** [comment]
creo que udalmap.R es una union de los 4 en un solo script y se supone que es la versión más actualizada.
este finde he intentado ejecutar otra vez el script para ver si me funcionaba despues de actualizar R, RStudio y los paquetes pero aun así la función "fortify" que se utiliza antes de hacer los graficos me sigue dando error y desde ahi en adelante ya no sigo.
investigaré un poco a ver porque me sucede esto. @gkobeaga tu no tienes este problema? sabes porque puede ser?

**Comment by numeroteca** [comment]
A mi me pasa lo mismo, me da error aquí:
```
> udalerriak_eae.map <- fortify(udalerriak_eae.shape, region="name")
Error: isTRUE(gpclibPermitStatus()) is not TRUE
```

**Comment by numeroteca** [comment]
Me funcionó finalmente... lo que pasa es que he probado tantas cosas a la vez que no sé cuál ha sido la solución real. @Haxier tienes instalado` library("gpclib")`?

**Comment by Haxier** [comment]
ok, parece que el problema venía de ahí. Aun así, aparte de instalar y de cargar el paquete gpclib también he tenido que ejecutar el comando gpclibPermit() antes de la funcion fortify()

**Comment by Haxier** [comment]
También había otro error, en las lineas 172 y 173 faltan dos cierres de corchetes } } uno para el "if()" superior y otro para el for()
Con estas correcciones ya me funciona bien el script. Ahora me pongo a hacer un documento en Rmd como tutorial metiendo texto explicativo

**Comment by gkobeaga** [comment]
No debería hacer falta abrir y cerrar los corchetes para el for, porqué el if "ocupa" todo el for, es como si hubiera una única linea. Os da error por eso? Puede ser que no le gusta a Rstudio cuando se ejecuta el script linea por linea. Os sigue dando el error cuando ejecutáis el script entero?

**Comment by numeroteca** [comment]
A mi el error no me sale al ejecutar línea por línea.

**Comment by gkobeaga** [comment]
Tenéis instalado **rgeos**. Yo no tengo instalado "gpclib" y me estaba funcionando, ahora me está dando error. Maptools sugiere tener instaldo rgeos.
https://cran.r-project.org/web/packages/maptools/index.html
