### ISSUE TITLE
Cómo hacer los en udalmap gráficos con título en castellano

### ISSUE THREAD

**Issue by numeroteca** [BilbaoDataLab/udalmap-r-maps#3]
He visto que hay [una variable `language`](https://github.com/BilbaoDataLab/session-20161027-r/blob/master/udalmap/udalmap.R#L14) en la url que se parsea desde el script `language1=1` ¿basta con cambiar ahí de 1 a 0 para obtener en castellano?

**Comment by gkobeaga** [comment]
Eso es, language1=0 en castellano, y language1=2 en ingles. También hay que cambiar las lineas 105-108. Se puede crear una variable lenguage al principio, y hacer la clasificación de tipo de variable (perc, eur, index, m2) según el lenguaje escogido.

**Comment by gkobeaga** [comment]
Ahora basta con cambiar el valor de la variable **language** al principio del script 30edbc206fdaa66fc97c54f8633e5732fc3e0440 .

**Comment by numeroteca** [comment]
Se podrían guardar en carpetas diferentes para que cuando lo corres en el otro idioma no te sobreescriba ¿cómo lo ves?

**Comment by gkobeaga** [comment]
Sí mejor!

Estoy metiendo las figuras producidas en la carpeta out, para subir al
repositorio y compartirlos. Se pueden escribir en esa misma carpeta
también, en vez de en la raíz. Como veas.
