### ISSUE TITLE
Separar repositorios

### ISSUE THREAD

**Issue by numeroteca** [BilbaoDataLab/udalmap-r-maps#4]
Después de haber probado los scripts sugiero separar las dos sesiones (intro a R y Udalmap) en dos repositorios diferentes, para mayor claridad.
Dejaría Udalmap en este repo y abriría uno para intro a R que hizo @Haxier.

Para ello necesito que me deis permiso para editar en este repo, de paso le cambiaré el nombre session-20161027-r. Tengo unos cambios hechos que añaden comentarios al script de @gkobeaga y quería publicarlos.

**Comment by Haxier** [comment]
te he hecho la invitacion a colaborar en el repositorio

**Comment by numeroteca** [comment]
El repo con el tutorial de introducción a R de @Haxier está ahora disponible en https://github.com/BilbaoDataLab/intro-tutorial-r

**Comment by numeroteca** [comment]
Este repo ha sido renombrado como  `udalmap-r-maps` en vez de `session-20161027-r`
