### ISSUE TITLE
Falta por comitear los shapefiles y algún que otro archivo

### ISSUE THREAD

**Issue by numeroteca** [BilbaoDataLab/udalmap-r-maps#5]
¿Falta por subir algunos archivos como los shapefiles?

https://github.com/BilbaoDataLab/udalmap-r-maps/blob/d8d6c2615c3785d2dbf8b0e968ac892fbabbc18f/src/udalmap-eskualdeka.R#L41

**Comment by gkobeaga** [comment]
Esa linea estaba de sobra. Los shp descarga el script si no estan descagados ya.

https://github.com/BilbaoDataLab/udalmap-r-maps/blob/888c1770fc64c0593a98315615d98c677035685e/src/udalmap-udalerrika.R#L29-L35
